title: Haha Hot Dogs
email: hahahotdogs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Haha Hot Dogs is a postcard company that also creates good times through other fun hot dog art.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "hahahotdogs.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  heymarkwetzel
timezone: America/Chicago
permalink: /:title/
markdown: kramdown

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-feed

exclude: [README.md, Gemfile, Gemfile.lock]
