list:

  - title: Koozies
    description: Hold your drink. With a hot dog.
    thumbnail: /assets/images/product-thumbnails/koozies.jpg
    url: /koozies/

  - title: Pins
    description: Wear the hot dogs you want to see in the world.
    thumbnail: /assets/images/product-thumbnails/pins.jpg
    url: /pins/

  - title: Postcards
    description: Quit Facebook, write penpals.
    thumbnail: /assets/images/product-thumbnails/postcards.jpg
    url: /postcards/

  - title: Prints
    description: Hot dogs on the wall.
    thumbnail: /assets/images/product-thumbnails/prints.jpg
    url: /prints/

  - title: Stickers
    description: When sticky fingers are a good thing.
    thumbnail: /assets/images/product-thumbnails/stickers.jpg
    url: /stickers/

  - title: Haha Postcard Club
    description: One postcard per month for the entire year.
    thumbnail: /assets/images/product-thumbnails/postcard-club.jpg
    url: /postcard-club/
